import type { PortalRole, PortalWorkspace, Visibility } from './types';
import { canRoleSee, isBotChainRole, isKlineoRole, isProjectRole } from './visibility';

const BASE_WORKSPACE: PortalWorkspace = {
  user: {
    id: 'user-klineo-1',
    email: 'maya@klineo.xyz',
    fullName: 'Maya Chen',
    role: 'klineo_admin',
    organizationName: 'Klineo',
  },
  projects: [
    {
      id: 'project-atlas',
      slug: 'atlas-pay',
      name: 'Atlas Pay',
      tagline: 'Programmable settlement for autonomous commerce.',
      description:
        'Atlas Pay gives agents policy-bound wallets, checkout primitives, and a transparent settlement layer for machine-to-machine transactions.',
      stage: 'integration_ready',
      progressPercent: 78,
      cohortName: 'Launch Cohort 01',
      targetLaunchAt: '2026-09-14T09:00:00.000Z',
      lastUpdateAt: '2026-08-15T14:30:00.000Z',
      websiteUrl: 'https://example.com/atlas',
      demoUrl: 'https://example.com/atlas/demo',
      repositoryUrl: 'https://github.com/example/atlas',
      videoUrl: null,
      documentationUrl: 'https://example.com/atlas/docs',
      integrationReadiness: 'ready',
      liquidityReadiness: 'in_progress',
      launchReadiness: 'in_progress',
      accent: '#d8ff62',
    },
    {
      id: 'project-ember',
      slug: 'ember-works',
      name: 'Ember Works',
      tagline: 'Composable identity for useful agents.',
      description:
        'Ember Works issues verifiable identities and scoped capabilities to teams deploying autonomous agents across organizations.',
      stage: 'cohort',
      progressPercent: 61,
      cohortName: 'Launch Cohort 01',
      targetLaunchAt: '2026-10-05T09:00:00.000Z',
      lastUpdateAt: '2026-08-11T10:15:00.000Z',
      websiteUrl: 'https://example.com/ember',
      demoUrl: null,
      repositoryUrl: 'https://github.com/example/ember',
      videoUrl: 'https://example.com/ember/walkthrough',
      documentationUrl: null,
      integrationReadiness: 'in_progress',
      liquidityReadiness: 'not_started',
      launchReadiness: 'in_progress',
      accent: '#ff7657',
    },
    {
      id: 'project-fluent',
      slug: 'fluent-markets',
      name: 'Fluent Markets',
      tagline: 'Intent-native liquidity routing.',
      description:
        'Fluent finds and executes policy-compatible liquidity routes for agent treasuries while keeping every decision inspectable.',
      stage: 'liquidity_ready',
      progressPercent: 86,
      cohortName: 'Launch Cohort 01',
      targetLaunchAt: '2026-08-29T09:00:00.000Z',
      lastUpdateAt: '2026-08-16T08:45:00.000Z',
      websiteUrl: 'https://example.com/fluent',
      demoUrl: 'https://example.com/fluent/app',
      repositoryUrl: null,
      videoUrl: null,
      documentationUrl: 'https://example.com/fluent/docs',
      integrationReadiness: 'ready',
      liquidityReadiness: 'ready',
      launchReadiness: 'in_progress',
      accent: '#82a7ff',
    },
    {
      id: 'project-nori',
      slug: 'nori-labs',
      name: 'Nori Labs',
      tagline: 'Private inference receipts for open networks.',
      description:
        'Nori proves that an inference met a declared policy without publishing private inputs, intermediate state, or model credentials.',
      stage: 'screening',
      progressPercent: 34,
      cohortName: null,
      targetLaunchAt: null,
      lastUpdateAt: '2026-07-29T16:00:00.000Z',
      websiteUrl: 'https://example.com/nori',
      demoUrl: null,
      repositoryUrl: null,
      videoUrl: null,
      documentationUrl: null,
      integrationReadiness: 'blocked',
      liquidityReadiness: 'not_started',
      launchReadiness: 'not_started',
      accent: '#d5b5ff',
    },
  ],
  progressUpdates: [
    {
      id: 'update-atlas-8',
      projectId: 'project-atlas',
      version: 8,
      title: 'Settlement sandbox is live',
      summary:
        'The complete checkout-to-settlement path now runs against the BOT Chain integration sandbox, including retry and reconciliation states.',
      accomplishments: [
        'Completed policy-bound wallet provisioning',
        'Added settlement reconciliation receipts',
        'Reduced sandbox checkout latency by 31%',
      ],
      nextSteps: ['Complete liquidity rehearsal', 'Publish integrator quickstart'],
      progressPercent: 78,
      integrationReadiness: 'ready',
      liquidityReadiness: 'in_progress',
      launchReadiness: 'in_progress',
      visibility: 'bot_chain',
      submittedAt: '2026-08-15T14:30:00.000Z',
      submittedByName: 'Lina Ortiz',
      contentDigest: 'sha256:1d8dd2f0a2b8d6f94a3b821b79b75d8d',
    },
    {
      id: 'update-atlas-7',
      projectId: 'project-atlas',
      version: 7,
      title: 'Policy engine edge cases closed',
      summary:
        'We closed the remaining signer rotation and duplicate settlement edge cases from Klineo review.',
      accomplishments: ['Signer rotation tests', 'Idempotency audit', 'Updated threat model'],
      nextSteps: ['BOT Chain sandbox test'],
      progressPercent: 69,
      integrationReadiness: 'in_progress',
      liquidityReadiness: 'not_started',
      launchReadiness: 'in_progress',
      visibility: 'project_and_klineo',
      submittedAt: '2026-08-08T12:00:00.000Z',
      submittedByName: 'Lina Ortiz',
      contentDigest: 'sha256:df4a1d820f63e855aa46c778401e7f71',
    },
    {
      id: 'update-ember-5',
      projectId: 'project-ember',
      version: 5,
      title: 'Capability delegation prototype',
      summary:
        'The agent identity console now supports time-bound delegation with a human-readable policy preview.',
      accomplishments: ['Delegation prototype', 'Policy preview', 'Five partner interviews'],
      nextSteps: ['External audit scope', 'BOT Chain identity adapter'],
      progressPercent: 61,
      integrationReadiness: 'in_progress',
      liquidityReadiness: 'not_started',
      launchReadiness: 'in_progress',
      visibility: 'project_and_klineo',
      submittedAt: '2026-08-11T10:15:00.000Z',
      submittedByName: 'Sam Adeyemi',
      contentDigest: 'sha256:aa4029ea9622280383861f08327d0c9a',
    },
    {
      id: 'update-fluent-9',
      projectId: 'project-fluent',
      version: 9,
      title: 'Liquidity rehearsal passed',
      summary:
        'The team completed the first full rehearsal with guardrails, rollback checks, and market-health monitoring enabled.',
      accomplishments: ['Pool rehearsal', 'Slippage guardrails', 'Market-health alerts'],
      nextSteps: ['Final launch gate', 'Publish operator runbook'],
      progressPercent: 86,
      integrationReadiness: 'ready',
      liquidityReadiness: 'ready',
      launchReadiness: 'in_progress',
      visibility: 'bot_chain',
      submittedAt: '2026-08-16T08:45:00.000Z',
      submittedByName: 'Nora Voss',
      contentDigest: 'sha256:9af74ba76e2fb8b034f59b3d75de31d6',
    },
    {
      id: 'update-nori-2',
      projectId: 'project-nori',
      version: 2,
      title: 'Circuit benchmark notes',
      summary:
        'Private benchmark results and open questions for the Klineo technical screening team.',
      accomplishments: ['Benchmark harness', 'Proof-size comparison'],
      nextSteps: ['Resolve verifier performance blocker'],
      progressPercent: 34,
      integrationReadiness: 'blocked',
      liquidityReadiness: 'not_started',
      launchReadiness: 'not_started',
      visibility: 'project_private',
      submittedAt: '2026-07-29T16:00:00.000Z',
      submittedByName: 'Ivo Marin',
      contentDigest: 'sha256:10e8da53fecf1efea75a73a984782ac2',
    },
  ],
  milestones: [
    {
      id: 'milestone-a1',
      projectId: 'project-atlas',
      title: 'BOT Chain sandbox certification',
      category: 'Integration',
      status: 'completed',
      dueAt: '2026-08-14T17:00:00.000Z',
      ownerName: 'Lina Ortiz',
      evidenceUrl: 'https://example.com/atlas/evidence/sandbox',
      visibility: 'bot_chain',
    },
    {
      id: 'milestone-a2',
      projectId: 'project-atlas',
      title: 'Liquidity operations rehearsal',
      category: 'Liquidity',
      status: 'in_progress',
      dueAt: '2026-08-24T17:00:00.000Z',
      ownerName: 'Tomas Reid',
      evidenceUrl: null,
      visibility: 'project_and_klineo',
    },
    {
      id: 'milestone-a3',
      projectId: 'project-atlas',
      title: 'Public integrator quickstart',
      category: 'Documentation',
      status: 'not_started',
      dueAt: '2026-09-02T17:00:00.000Z',
      ownerName: 'Priya Shah',
      evidenceUrl: null,
      visibility: 'project_and_klineo',
    },
    {
      id: 'milestone-e1',
      projectId: 'project-ember',
      title: 'External security review scope',
      category: 'Security',
      status: 'blocked',
      dueAt: '2026-08-18T17:00:00.000Z',
      ownerName: 'Sam Adeyemi',
      evidenceUrl: null,
      visibility: 'project_and_klineo',
    },
    {
      id: 'milestone-f1',
      projectId: 'project-fluent',
      title: 'Liquidity rehearsal',
      category: 'Liquidity',
      status: 'completed',
      dueAt: '2026-08-15T17:00:00.000Z',
      ownerName: 'Nora Voss',
      evidenceUrl: 'https://example.com/fluent/rehearsal',
      visibility: 'bot_chain',
    },
    {
      id: 'milestone-n1',
      projectId: 'project-nori',
      title: 'Verifier performance target',
      category: 'Product',
      status: 'blocked',
      dueAt: '2026-08-05T17:00:00.000Z',
      ownerName: 'Ivo Marin',
      evidenceUrl: null,
      visibility: 'project_private',
    },
  ],
  blockers: [
    {
      id: 'blocker-a1',
      projectId: 'project-atlas',
      title: 'Test liquidity allocation',
      detail: 'The final rehearsal is waiting on confirmation of the sandbox allocation window.',
      severity: 'medium',
      status: 'monitoring',
      ownerName: 'Tomas Reid',
      visibility: 'bot_chain',
      createdAt: '2026-08-14T09:00:00.000Z',
    },
    {
      id: 'blocker-e1',
      projectId: 'project-ember',
      title: 'Security reviewer availability',
      detail: 'The preferred reviewer cannot begin until the last week of August.',
      severity: 'high',
      status: 'open',
      ownerName: 'Sam Adeyemi',
      visibility: 'project_and_klineo',
      createdAt: '2026-08-10T09:00:00.000Z',
    },
    {
      id: 'blocker-n1',
      projectId: 'project-nori',
      title: 'Verifier misses latency target',
      detail: 'The current proof verifier is 2.4× above the program target on commodity hardware.',
      severity: 'critical',
      status: 'open',
      ownerName: 'Ivo Marin',
      visibility: 'project_private',
      createdAt: '2026-07-28T09:00:00.000Z',
    },
  ],
  showcaseItems: [
    {
      id: 'showcase-a1',
      projectId: 'project-atlas',
      type: 'screenshot',
      title: 'Settlement control room',
      description: 'Live settlement state, policy checks, and reconciliation receipts.',
      url: null,
      visibility: 'bot_chain',
      status: 'approved',
      createdAt: '2026-08-15T14:40:00.000Z',
      assets: [
        {
          id: 'asset-a1',
          showcaseItemId: 'showcase-a1',
          projectId: 'project-atlas',
          storagePath: 'demo/atlas-console.svg',
          fileName: 'atlas-console.svg',
          mimeType: 'image/svg+xml',
          sizeBytes: 4280,
          width: 1440,
          height: 900,
          signedUrl: '/demo/atlas-console.svg',
        },
      ],
    },
    {
      id: 'showcase-a2',
      projectId: 'project-atlas',
      type: 'demo',
      title: 'Sandbox checkout demo',
      description: 'A guided checkout-to-settlement walkthrough for Klineo reviewers.',
      url: 'https://example.com/atlas/demo',
      visibility: 'project_and_klineo',
      status: 'submitted',
      createdAt: '2026-08-15T14:42:00.000Z',
      assets: [],
    },
    {
      id: 'showcase-e1',
      projectId: 'project-ember',
      type: 'video',
      title: 'Delegation policy walkthrough',
      description: 'Three-minute review of the human-readable delegation preview.',
      url: 'https://example.com/ember/walkthrough',
      visibility: 'project_and_klineo',
      status: 'changes_requested',
      createdAt: '2026-08-11T10:30:00.000Z',
      assets: [],
    },
    {
      id: 'showcase-f1',
      projectId: 'project-fluent',
      type: 'screenshot',
      title: 'Intent route inspector',
      description: 'Policy-compatible route selection and pre-trade guardrails.',
      url: null,
      visibility: 'public',
      status: 'approved',
      createdAt: '2026-08-16T09:00:00.000Z',
      assets: [
        {
          id: 'asset-f1',
          showcaseItemId: 'showcase-f1',
          projectId: 'project-fluent',
          storagePath: 'demo/fluent-market.svg',
          fileName: 'fluent-market.svg',
          mimeType: 'image/svg+xml',
          sizeBytes: 4210,
          width: 1440,
          height: 900,
          signedUrl: '/demo/fluent-market.svg',
        },
      ],
    },
  ],
  comments: [
    {
      id: 'comment-1',
      projectId: 'project-atlas',
      subjectType: 'progress_update',
      subjectId: 'update-atlas-8',
      body: 'The retry evidence is clear. Please add the final liquidity rehearsal receipt before launch review.',
      authorName: 'Maya Chen',
      authorRole: 'klineo_reviewer',
      visibility: 'project_and_klineo',
      createdAt: '2026-08-15T16:10:00.000Z',
    },
    {
      id: 'comment-2',
      projectId: 'project-atlas',
      subjectType: 'progress_update',
      subjectId: 'update-atlas-8',
      body: 'Acknowledged. The integration path is ready from the partner review side.',
      authorName: 'Arda Kaya',
      authorRole: 'bot_chain_reviewer',
      visibility: 'bot_chain',
      createdAt: '2026-08-16T09:20:00.000Z',
    },
    {
      id: 'comment-3',
      projectId: 'project-ember',
      subjectType: 'showcase_item',
      subjectId: 'showcase-e1',
      body: 'Please remove the test user email visible at 01:42, then resubmit.',
      authorName: 'Maya Chen',
      authorRole: 'klineo_reviewer',
      visibility: 'project_and_klineo',
      createdAt: '2026-08-12T11:00:00.000Z',
    },
  ],
  reviewRequests: [
    {
      id: 'review-a1',
      projectId: 'project-atlas',
      subjectType: 'milestone',
      subjectId: 'milestone-a2',
      title: 'Liquidity rehearsal review',
      status: 'in_review',
      requestedAt: '2026-08-15T14:35:00.000Z',
      dueAt: '2026-08-20T17:00:00.000Z',
      requestedByName: 'Lina Ortiz',
      assignedToName: 'Maya Chen',
    },
    {
      id: 'review-e1',
      projectId: 'project-ember',
      subjectType: 'showcase_item',
      subjectId: 'showcase-e1',
      title: 'Delegation walkthrough showcase',
      status: 'changes_requested',
      requestedAt: '2026-08-11T10:31:00.000Z',
      dueAt: '2026-08-18T17:00:00.000Z',
      requestedByName: 'Sam Adeyemi',
      assignedToName: 'Maya Chen',
    },
    {
      id: 'review-f1',
      projectId: 'project-fluent',
      subjectType: 'gate',
      subjectId: 'launch-readiness',
      title: 'Final launch gate',
      status: 'requested',
      requestedAt: '2026-08-16T09:10:00.000Z',
      dueAt: '2026-08-21T17:00:00.000Z',
      requestedByName: 'Nora Voss',
      assignedToName: null,
    },
  ],
  visibilityApprovals: [
    {
      id: 'approval-1',
      projectId: 'project-atlas',
      subjectType: 'showcase_item',
      subjectId: 'showcase-a2',
      fromVisibility: 'project_and_klineo',
      toVisibility: 'bot_chain',
      status: 'requested',
      requestedByName: 'Lina Ortiz',
      requestedAt: '2026-08-15T15:00:00.000Z',
      decidedByName: null,
      decidedAt: null,
    },
    {
      id: 'approval-2',
      projectId: 'project-fluent',
      subjectType: 'showcase_item',
      subjectId: 'showcase-f1',
      fromVisibility: 'bot_chain',
      toVisibility: 'public',
      status: 'approved',
      requestedByName: 'Nora Voss',
      requestedAt: '2026-08-14T09:00:00.000Z',
      decidedByName: 'Maya Chen',
      decidedAt: '2026-08-15T11:20:00.000Z',
    },
  ],
  cohorts: [
    {
      id: 'cohort-1',
      name: 'Launch Cohort 01',
      status: 'active',
      startsOn: '2026-07-06',
      endsOn: '2026-10-16',
      projectIds: ['project-atlas', 'project-ember', 'project-fluent'],
    },
  ],
  desktopSubmissionImports: [
    {
      id: 'desktop-import-atlas-1',
      projectId: 'project-atlas',
      localProjectId: 'local-atlas-pay',
      schemaVersion: 1,
      contentDigest: 'sha256:6a4da3f590f8be0b7c2b811e13f2f8d1',
      importedAt: '2026-08-15T13:50:00.000Z',
    },
  ],
  auditEvents: [
    {
      id: 'audit-1',
      projectId: 'project-fluent',
      actorName: 'Maya Chen',
      action: 'visibility.approved',
      detail: 'Approved “Intent route inspector” for the public showcase.',
      createdAt: '2026-08-15T11:20:00.000Z',
    },
    {
      id: 'audit-2',
      projectId: 'project-atlas',
      actorName: 'Lina Ortiz',
      action: 'progress.submitted',
      detail: 'Submitted progress update v8 with BOT Chain visibility.',
      createdAt: '2026-08-15T14:30:00.000Z',
    },
    {
      id: 'audit-3',
      projectId: 'project-ember',
      actorName: 'Maya Chen',
      action: 'showcase.changes_requested',
      detail: 'Requested metadata redaction in the delegation walkthrough.',
      createdAt: '2026-08-12T11:00:00.000Z',
    },
  ],
};

const roleProfiles: Record<PortalRole, PortalWorkspace['user']> = {
  klineo_admin: BASE_WORKSPACE.user,
  klineo_operator: {
    ...BASE_WORKSPACE.user,
    id: 'user-klineo-2',
    email: 'ops@klineo.xyz',
    fullName: 'Klineo Operations',
    role: 'klineo_operator',
  },
  klineo_reviewer: {
    ...BASE_WORKSPACE.user,
    id: 'user-klineo-3',
    email: 'review@klineo.xyz',
    fullName: 'Klineo Reviewer',
    role: 'klineo_reviewer',
  },
  bot_chain_reviewer: {
    id: 'user-bot-1',
    email: 'review@botchain.example',
    fullName: 'Arda Kaya',
    role: 'bot_chain_reviewer',
    organizationName: 'BOT Chain',
  },
  bot_chain_viewer: {
    id: 'user-bot-2',
    email: 'program@botchain.example',
    fullName: 'BOT Chain Program',
    role: 'bot_chain_viewer',
    organizationName: 'BOT Chain',
  },
  project_lead: {
    id: 'user-atlas-1',
    email: 'lina@atlas.example',
    fullName: 'Lina Ortiz',
    role: 'project_lead',
    organizationName: 'Atlas Pay',
  },
  project_member: {
    id: 'user-atlas-2',
    email: 'team@atlas.example',
    fullName: 'Atlas Product Team',
    role: 'project_member',
    organizationName: 'Atlas Pay',
  },
};

function projectScoped<T extends { projectId: string; visibility: Visibility }>(
  items: T[],
  role: PortalRole,
): T[] {
  return items.filter(
    (item) =>
      canRoleSee(role, item.visibility) &&
      (!isProjectRole(role) || item.projectId === 'project-atlas'),
  );
}

export function createDemoWorkspace(role: PortalRole = 'klineo_admin'): PortalWorkspace {
  const visibleProjects = isProjectRole(role)
    ? BASE_WORKSPACE.projects.filter((project) => project.id === 'project-atlas')
    : isBotChainRole(role)
      ? BASE_WORKSPACE.projects.filter((project) =>
          [
            ...BASE_WORKSPACE.progressUpdates,
            ...BASE_WORKSPACE.milestones,
            ...BASE_WORKSPACE.blockers,
            ...BASE_WORKSPACE.showcaseItems,
          ].some((item) => item.projectId === project.id && canRoleSee(role, item.visibility)),
        )
      : BASE_WORKSPACE.projects;
  const projectIds = new Set(visibleProjects.map((project) => project.id));

  return structuredClone({
    ...BASE_WORKSPACE,
    user: roleProfiles[role],
    projects: visibleProjects,
    progressUpdates: projectScoped(BASE_WORKSPACE.progressUpdates, role),
    milestones: projectScoped(BASE_WORKSPACE.milestones, role),
    blockers: projectScoped(BASE_WORKSPACE.blockers, role),
    showcaseItems: projectScoped(BASE_WORKSPACE.showcaseItems, role),
    comments: BASE_WORKSPACE.comments.filter(
      (comment) =>
        projectIds.has(comment.projectId) &&
        comment.visibility !== 'klineo_internal' &&
        canRoleSee(role, comment.visibility),
    ),
    reviewRequests: BASE_WORKSPACE.reviewRequests.filter(
      (review) => projectIds.has(review.projectId) && !isBotChainRole(role),
    ),
    visibilityApprovals:
      isKlineoRole(role) || isProjectRole(role)
        ? BASE_WORKSPACE.visibilityApprovals.filter((approval) =>
            projectIds.has(approval.projectId),
          )
        : [],
    cohorts: BASE_WORKSPACE.cohorts.map((cohort) => ({
      ...cohort,
      projectIds: cohort.projectIds.filter((projectId) => projectIds.has(projectId)),
    })),
    desktopSubmissionImports: BASE_WORKSPACE.desktopSubmissionImports.filter(
      (item) => projectIds.has(item.projectId) && !isBotChainRole(role),
    ),
    auditEvents: isKlineoRole(role)
      ? BASE_WORKSPACE.auditEvents
      : BASE_WORKSPACE.auditEvents.filter((event) =>
          event.projectId ? projectIds.has(event.projectId) : false,
        ),
  });
}
